import { StyleSheet } from "react-native";

import {
  BORDER_RADIUS,
  FONT_SIZE,
  SPACING,
  type ThemeColors,
} from "../../theme";

export const createStatisticsStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: { padding: SPACING.lg, paddingBottom: 0 },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: SPACING.lg,
      paddingBottom: 0,
      gap: SPACING.sm,
    },
    headerFlex: { flex: 1 },
    refreshButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      boxShadow: "0px 4px 10px rgba(139, 92, 246, 0.3)",
      elevation: 3,
    },
    periodTabs: {
      flexDirection: "row",
      backgroundColor: colors.primary,
      borderRadius: BORDER_RADIUS.xl,
      padding: 3,
    },
    periodTab: {
      flex: 1,
      paddingVertical: SPACING.sm,
      alignItems: "center",
      borderRadius: BORDER_RADIUS.lg,
    },
    periodTabActive: { backgroundColor: "rgba(255,255,255,0.2)" },
    periodTabText: {
      fontSize: FONT_SIZE.sm,
      color: "rgba(255,255,255,0.7)",
      fontWeight: "600",
    },
    periodTabTextActive: { color: colors.white, fontWeight: "700" },
    dateNav: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: SPACING.lg,
    },
    navButton: {
      width: 44,
      height: 44,
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.md,
      justifyContent: "center",
      alignItems: "center",
    },
    navButtonText: {
      fontSize: FONT_SIZE.xl,
      color: colors.primary,
      fontWeight: "600",
    },
    datePickerButton: {
      flex: 1,
      marginHorizontal: SPACING.md,
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.md,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
    },
    dateText: {
      textAlign: "center",
      fontSize: FONT_SIZE.md,
      fontWeight: "700",
      color: colors.primary,
    },
    dateHint: {
      marginTop: 2,
      textAlign: "center",
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
    },
    content: { flex: 1, paddingHorizontal: SPACING.lg },
    card: {
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.xl,
      padding: SPACING.lg,
      marginBottom: SPACING.lg,
      borderWidth: 0.5,
      borderColor: colors.border,
      boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.04)",
      elevation: 2,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: SPACING.md,
      gap: SPACING.sm,
    },
    cardHeaderInfo: { flex: 1 },
    cardTitle: {
      fontSize: FONT_SIZE.lg,
      fontWeight: "700",
      color: colors.text,
    },
    cardSubtitle: {
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
      marginTop: 2,
      marginBottom: SPACING.sm,
    },
    cardBlacklist: {
      borderColor: colors.danger + "55",
      backgroundColor: colors.danger + "06",
    },
    rangeLabel: {
      marginTop: 4,
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
    },
    rangeActions: {
      flexDirection: "row",
      gap: SPACING.sm,
      marginBottom: SPACING.md,
    },
    rangeButton: {
      flex: 1,
      backgroundColor: colors.surfaceSecondary,
      borderRadius: BORDER_RADIUS.md,
      padding: SPACING.md,
    },
    rangeButtonLabel: {
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    rangeButtonValue: {
      fontSize: FONT_SIZE.sm,
      fontWeight: "700",
      color: colors.text,
    },
    resetButton: {
      backgroundColor: colors.surfaceSecondary,
      borderRadius: BORDER_RADIUS.full,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
    },
    resetButtonText: {
      fontSize: FONT_SIZE.xs,
      fontWeight: "700",
      color: colors.primary,
    },
    statsGrid: { flexDirection: "row", flexWrap: "wrap" },
    statItem: { width: "50%", marginBottom: SPACING.lg },
    statLabel: { fontSize: FONT_SIZE.sm, color: colors.textSecondary },
    statValue: {
      fontSize: FONT_SIZE.lg,
      fontWeight: "700",
      color: colors.text,
    },
    statValueHighlight: {
      fontSize: FONT_SIZE.lg,
      fontWeight: "800",
    },
    mainKPIContainer: {
      width: "100%",
      marginBottom: SPACING.md,
      paddingBottom: SPACING.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    mainKPIValue: {
      fontSize: 30,
      fontWeight: "800",
      letterSpacing: -0.5,
    },
    noDataText: {
      fontSize: FONT_SIZE.sm,
      color: colors.textTertiary,
      textAlign: "center",
      paddingTop: SPACING.sm,
    },
    rankItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: SPACING.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      gap: SPACING.sm,
    },
    rankBadge: {
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: "center",
      alignItems: "center",
    },
    rankBadgeText: {
      fontSize: FONT_SIZE.xs,
      fontWeight: "700",
    },
    rankInfo: { flex: 1 },
    rankName: { fontSize: FONT_SIZE.md, fontWeight: "600", color: colors.text },
    rankSub: { fontSize: FONT_SIZE.xs, color: colors.textSecondary },
    rankMetrics: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 2,
    },
    rankProfit: {
      fontSize: FONT_SIZE.sm,
      fontWeight: "700",
    },
    pickerOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "center",
      padding: SPACING.lg,
    },
    pickerModal: {
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.lg,
      padding: SPACING.lg,
    },
    pickerTitle: {
      fontSize: FONT_SIZE.lg,
      fontWeight: "700",
      color: colors.text,
      textAlign: "center",
    },
    pickerValue: {
      marginTop: SPACING.xs,
      marginBottom: SPACING.md,
      fontSize: FONT_SIZE.sm,
      color: colors.textSecondary,
      textAlign: "center",
    },
    calendarHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: SPACING.md,
    },
    calendarNavButton: {
      width: 40,
      height: 40,
      borderRadius: BORDER_RADIUS.md,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    calendarNavText: {
      fontSize: FONT_SIZE.xl,
      fontWeight: "700",
      color: colors.primary,
    },
    calendarMonthLabel: {
      fontSize: FONT_SIZE.md,
      fontWeight: "700",
      color: colors.text,
    },
    calendarWeekRow: {
      flexDirection: "row",
      marginBottom: SPACING.sm,
    },
    calendarWeekday: {
      width: "14.2857%",
      textAlign: "center",
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
      fontWeight: "600",
    },
    calendarGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
    },
    calendarDay: {
      width: "14.2857%",
      aspectRatio: 1,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: BORDER_RADIUS.md,
      marginVertical: SPACING.xs,
    },
    calendarDaySelected: {
      backgroundColor: colors.primary,
    },
    calendarDayText: {
      fontSize: FONT_SIZE.sm,
      color: colors.text,
      fontWeight: "600",
    },
    calendarDayTextMuted: {
      color: colors.textTertiary,
    },
    calendarDayTextSelected: {
      color: colors.white,
    },
    pickerActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: SPACING.sm,
      marginTop: SPACING.md,
    },
    pickerCancel: {
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.md,
      backgroundColor: colors.surfaceSecondary,
    },
    pickerCancelText: {
      color: colors.text,
      fontWeight: "600",
    },
    pickerSave: {
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.md,
      backgroundColor: colors.primary,
    },
    pickerSaveText: {
      color: colors.white,
      fontWeight: "700",
    },
    loadingContainer: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "center",
      alignItems: "center",
      zIndex: 999,
    },
    loadingText: {
      fontSize: FONT_SIZE.md,
      color: colors.textSecondary,
    },
    offlineBanner: {
      marginHorizontal: SPACING.lg,
      marginBottom: SPACING.sm,
      backgroundColor: colors.warning + "15",
      borderRadius: BORDER_RADIUS.lg,
      padding: SPACING.sm,
      borderWidth: 0.5,
      borderColor: colors.warning + "40",
    },
    offlineBannerText: {
      fontSize: FONT_SIZE.xs,
      color: colors.warning,
      textAlign: "center",
      fontWeight: "600",
    },
    profit: { color: colors.secondary },
    showMoreButton: {
      marginTop: SPACING.md,
      paddingVertical: SPACING.sm,
      borderRadius: BORDER_RADIUS.md,
      borderWidth: 1,
      borderColor: colors.primary + "30",
      alignItems: "center",
    },
    showMoreText: {
      fontSize: FONT_SIZE.sm,
      fontWeight: "700",
      color: colors.primary,
    },
    lockedContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: SPACING.xl,
    },
    lockedIconContainer: {
      width: 88,
      height: 88,
      borderRadius: 44,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: SPACING.lg,
    },
    lockedTitle: {
      fontSize: FONT_SIZE.xl,
      fontWeight: "700",
      marginBottom: SPACING.md,
      textAlign: "center",
    },
    lockedMessage: {
      fontSize: FONT_SIZE.md,
      textAlign: "center",
      lineHeight: 24,
      paddingHorizontal: SPACING.lg,
    },
    telegramButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: SPACING.sm,
      marginTop: SPACING.xl,
      paddingHorizontal: SPACING.xl,
      paddingVertical: SPACING.md,
      borderRadius: BORDER_RADIUS.xl,
      boxShadow: "0px 4px 12px rgba(0, 136, 204, 0.3)",
      elevation: 3,
    },
    telegramButtonText: {
      color: "#ffffff",
      fontSize: FONT_SIZE.md,
      fontWeight: "700",
    },
    allTimeModalRoot: { flex: 1 },
    allTimeHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: SPACING.lg,
      paddingVertical: SPACING.md,
      borderBottomWidth: 1,
    },
    allTimeTitle: {
      fontSize: FONT_SIZE.xl,
      fontWeight: "700",
      flex: 1,
    },
    allTimeClose: { padding: SPACING.sm },
    allTimeRangeRow: {
      flexDirection: "row",
      gap: SPACING.sm,
      padding: SPACING.lg,
    },
    applyRangeBtn: {
      marginHorizontal: SPACING.lg,
      paddingVertical: SPACING.md,
      borderRadius: BORDER_RADIUS.md,
      alignItems: "center",
      marginBottom: SPACING.sm,
    },
    applyRangeBtnText: {
      fontSize: FONT_SIZE.md,
      fontWeight: "700",
    },
    statsToolbar: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: SPACING.sm,
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.sm,
    },
    statsToolbarBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: SPACING.xs,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.lg,
      borderWidth: 0.5,
    },
    statsToolbarBtnText: {
      fontSize: FONT_SIZE.sm,
      fontWeight: "600",
    },
  });
