import { StyleSheet } from "react-native";

import {
  BORDER_RADIUS,
  FONT_SIZE,
  SPACING,
  type ThemeColors,
} from "../../theme";

export const createStatisticsStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: { padding: SPACING.lg, paddingBottom: 0 },
    periodTabs: {
      flexDirection: "row",
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.lg,
      padding: SPACING.xs,
    },
    periodTab: {
      flex: 1,
      paddingVertical: SPACING.sm,
      alignItems: "center",
      borderRadius: BORDER_RADIUS.md,
    },
    periodTabActive: { backgroundColor: colors.primary },
    periodTabText: {
      fontSize: FONT_SIZE.sm,
      color: colors.textSecondary,
      fontWeight: "500",
    },
    periodTabTextActive: { color: colors.white, fontWeight: "700" },
    dateNav: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: SPACING.lg,
    },
    navButton: {
      width: 44,
      height: 44,
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.md,
      justifyContent: "center",
      alignItems: "center",
    },
    navButtonText: {
      fontSize: FONT_SIZE.xl,
      color: colors.primary,
      fontWeight: "600",
    },
    datePickerButton: {
      flex: 1,
      marginHorizontal: SPACING.md,
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.md,
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
    },
    dateText: {
      textAlign: "center",
      fontSize: FONT_SIZE.md,
      fontWeight: "700",
      color: colors.text,
    },
    dateHint: {
      marginTop: 2,
      textAlign: "center",
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
    },
    content: { flex: 1, paddingHorizontal: SPACING.lg },
    card: {
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.lg,
      padding: SPACING.lg,
      marginBottom: SPACING.lg,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: SPACING.md,
      gap: SPACING.sm,
    },
    cardHeaderInfo: { flex: 1 },
    cardTitle: {
      fontSize: FONT_SIZE.lg,
      fontWeight: "700",
      color: colors.text,
    },
    rangeLabel: {
      marginTop: 4,
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
    },
    rangeActions: {
      flexDirection: "row",
      gap: SPACING.sm,
      marginBottom: SPACING.md,
    },
    rangeButton: {
      flex: 1,
      backgroundColor: colors.surfaceSecondary,
      borderRadius: BORDER_RADIUS.md,
      padding: SPACING.md,
    },
    rangeButtonLabel: {
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
      marginBottom: 4,
    },
    rangeButtonValue: {
      fontSize: FONT_SIZE.sm,
      fontWeight: "700",
      color: colors.text,
    },
    resetButton: {
      backgroundColor: colors.surfaceSecondary,
      borderRadius: BORDER_RADIUS.full,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
    },
    resetButtonText: {
      fontSize: FONT_SIZE.xs,
      fontWeight: "700",
      color: colors.primary,
    },
    statsGrid: { flexDirection: "row", flexWrap: "wrap" },
    statItem: { width: "50%", marginBottom: SPACING.lg },
    statLabel: { fontSize: FONT_SIZE.sm, color: colors.textSecondary },
    statValue: {
      fontSize: FONT_SIZE.lg,
      fontWeight: "700",
      color: colors.text,
    },
    statValueHighlight: {
      fontSize: FONT_SIZE.lg,
      fontWeight: "800",
    },
    mainKPIValue: {
      fontSize: 30,
      fontWeight: "800",
      letterSpacing: -0.5,
    },
    noDataText: {
      fontSize: FONT_SIZE.sm,
      color: colors.textTertiary,
      textAlign: "center",
      paddingTop: SPACING.sm,
    },
    rankItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: SPACING.sm,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    rankInfo: { flex: 1 },
    rankName: { fontSize: FONT_SIZE.md, fontWeight: "600", color: colors.text },
    rankSub: { fontSize: FONT_SIZE.xs, color: colors.textSecondary },
    pickerOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "center",
      padding: SPACING.lg,
    },
    pickerModal: {
      backgroundColor: colors.surface,
      borderRadius: BORDER_RADIUS.lg,
      padding: SPACING.lg,
    },
    pickerTitle: {
      fontSize: FONT_SIZE.lg,
      fontWeight: "700",
      color: colors.text,
      textAlign: "center",
    },
    pickerValue: {
      marginTop: SPACING.xs,
      marginBottom: SPACING.md,
      fontSize: FONT_SIZE.sm,
      color: colors.textSecondary,
      textAlign: "center",
    },
    calendarHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: SPACING.md,
    },
    calendarNavButton: {
      width: 40,
      height: 40,
      borderRadius: BORDER_RADIUS.md,
      backgroundColor: colors.surfaceSecondary,
      alignItems: "center",
      justifyContent: "center",
    },
    calendarNavText: {
      fontSize: FONT_SIZE.xl,
      fontWeight: "700",
      color: colors.primary,
    },
    calendarMonthLabel: {
      fontSize: FONT_SIZE.md,
      fontWeight: "700",
      color: colors.text,
    },
    calendarWeekRow: {
      flexDirection: "row",
      marginBottom: SPACING.xs,
    },
    calendarWeekday: {
      width: "14.2857%",
      textAlign: "center",
      fontSize: FONT_SIZE.xs,
      color: colors.textSecondary,
      fontWeight: "600",
    },
    calendarGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
    },
    calendarDay: {
      width: "14.2857%",
      aspectRatio: 1,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: BORDER_RADIUS.md,
      marginBottom: SPACING.xs,
    },
    calendarDaySelected: {
      backgroundColor: colors.primary,
    },
    calendarDayText: {
      fontSize: FONT_SIZE.sm,
      color: colors.text,
      fontWeight: "600",
    },
    calendarDayTextMuted: {
      color: colors.textTertiary,
    },
    calendarDayTextSelected: {
      color: colors.white,
    },
    pickerActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: SPACING.sm,
      marginTop: SPACING.md,
    },
    pickerCancel: {
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.md,
      backgroundColor: colors.surfaceSecondary,
    },
    pickerCancelText: {
      color: colors.text,
      fontWeight: "600",
    },
    pickerSave: {
      paddingVertical: SPACING.sm,
      paddingHorizontal: SPACING.md,
      borderRadius: BORDER_RADIUS.md,
      backgroundColor: colors.primary,
    },
    pickerSaveText: {
      color: colors.white,
      fontWeight: "700",
    },
    profit: { color: colors.secondary },
  });
