import { StyleSheet } from "react-native";

import { BORDER_RADIUS, COLORS, FONT_SIZE, SPACING } from "../../constants";

export const statisticsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: { padding: SPACING.lg, paddingBottom: 0 },
  periodTabs: {
    flexDirection: "row",
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.xs,
  },
  periodTab: {
    flex: 1,
    paddingVertical: SPACING.sm,
    alignItems: "center",
    borderRadius: BORDER_RADIUS.md,
  },
  periodTabActive: { backgroundColor: COLORS.primary },
  periodTabText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.textSecondary,
    fontWeight: "500",
  },
  periodTabTextActive: { color: COLORS.white, fontWeight: "700" },
  dateNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: SPACING.lg,
  },
  navButton: {
    width: 44,
    height: 44,
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.md,
    justifyContent: "center",
    alignItems: "center",
  },
  navButtonText: {
    fontSize: FONT_SIZE.xl,
    color: COLORS.primary,
    fontWeight: "600",
  },
  datePickerButton: {
    flex: 1,
    marginHorizontal: SPACING.md,
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.md,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
  },
  dateText: {
    textAlign: "center",
    fontSize: FONT_SIZE.md,
    fontWeight: "700",
    color: COLORS.text,
  },
  dateHint: {
    marginTop: 2,
    textAlign: "center",
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
  },
  content: { flex: 1, paddingHorizontal: SPACING.lg },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: SPACING.md,
    gap: SPACING.sm,
  },
  cardHeaderInfo: { flex: 1 },
  cardTitle: {
    fontSize: FONT_SIZE.lg,
    fontWeight: "700",
    color: COLORS.text,
  },
  rangeLabel: {
    marginTop: 4,
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
  },
  rangeActions: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  rangeButton: {
    flex: 1,
    backgroundColor: COLORS.surfaceSecondary,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
  },
  rangeButtonLabel: {
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  rangeButtonValue: {
    fontSize: FONT_SIZE.sm,
    fontWeight: "700",
    color: COLORS.text,
  },
  resetButton: {
    backgroundColor: COLORS.surfaceSecondary,
    borderRadius: BORDER_RADIUS.full,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  resetButtonText: {
    fontSize: FONT_SIZE.xs,
    fontWeight: "700",
    color: COLORS.primary,
  },
  statsGrid: { flexDirection: "row", flexWrap: "wrap" },
  statItem: { width: "50%", marginBottom: SPACING.lg },
  statLabel: { fontSize: FONT_SIZE.sm, color: COLORS.textSecondary },
  statValue: {
    fontSize: FONT_SIZE.lg,
    fontWeight: "700",
    color: COLORS.text,
  },
  noDataText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.textTertiary,
    textAlign: "center",
    paddingTop: SPACING.sm,
  },
  rankItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  rankNum: {
    width: 28,
    fontSize: FONT_SIZE.lg,
    fontWeight: "700",
    color: COLORS.primary,
  },
  rankInfo: { flex: 1 },
  rankName: { fontSize: FONT_SIZE.md, fontWeight: "600", color: COLORS.text },
  rankSub: { fontSize: FONT_SIZE.xs, color: COLORS.textSecondary },
  pickerOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: "center",
    padding: SPACING.lg,
  },
  pickerModal: {
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.lg,
  },
  pickerTitle: {
    fontSize: FONT_SIZE.lg,
    fontWeight: "700",
    color: COLORS.text,
    textAlign: "center",
  },
  pickerValue: {
    marginTop: SPACING.xs,
    marginBottom: SPACING.md,
    fontSize: FONT_SIZE.sm,
    color: COLORS.textSecondary,
    textAlign: "center",
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
  },
  calendarNavButton: {
    width: 40,
    height: 40,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.surfaceSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarNavText: {
    fontSize: FONT_SIZE.xl,
    fontWeight: "700",
    color: COLORS.primary,
  },
  calendarMonthLabel: {
    fontSize: FONT_SIZE.md,
    fontWeight: "700",
    color: COLORS.text,
  },
  calendarWeekRow: {
    flexDirection: "row",
    marginBottom: SPACING.xs,
  },
  calendarWeekday: {
    width: "14.2857%",
    textAlign: "center",
    fontSize: FONT_SIZE.xs,
    color: COLORS.textSecondary,
    fontWeight: "600",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  calendarDay: {
    width: "14.2857%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: BORDER_RADIUS.md,
    marginBottom: SPACING.xs,
  },
  calendarDaySelected: {
    backgroundColor: COLORS.primary,
  },
  calendarDayText: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.text,
    fontWeight: "600",
  },
  calendarDayTextMuted: {
    color: COLORS.textTertiary,
  },
  calendarDayTextSelected: {
    color: COLORS.white,
  },
  pickerActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  pickerCancel: {
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.surfaceSecondary,
  },
  pickerCancelText: {
    color: COLORS.text,
    fontWeight: "600",
  },
  pickerSave: {
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.primary,
  },
  pickerSaveText: {
    color: COLORS.white,
    fontWeight: "700",
  },
  profit: { color: COLORS.secondary },
});
